"""add all_models

Revision ID: 660c4b13cbc1
Revises: 8ba9ac099174
Create Date: 2022-11-28 13:03:51.641630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660c4b13cbc1'
down_revision = '8ba9ac099174'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producer_filter', sa.Column('all_models', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producer_filter', 'all_models')
    # ### end Alembic commands ###
