version: "3"
services:
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.dev
    container_name: client-dev-c
    volumes:
      - ./app/frontend:/frontend
      - node_modules:/frontend/node_modules/
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
volumes:
  node_modules: