"""add advertisement status

Revision ID: 068681eb45b1
Revises: aadb91e45087
Create Date: 2022-11-14 09:23:37.755128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import enum

class AdvertisementStateEnum(enum.Enum):
    approved = "approved"
    rejected = "rejected"
    draft = "draft"


# revision identifiers, used by Alembic.
revision = '068681eb45b1'
down_revision = 'aadb91e45087'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advertisement_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['adv.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    advertisementstateenum = postgresql.ENUM(AdvertisementStateEnum, name='advertisementstateenum')
    advertisementstateenum.create(op.get_bind(), checkfirst=True)
    op.add_column('adv', sa.Column('status', advertisementstateenum, server_default='draft', nullable=False))
    op.add_column('adv', sa.Column('pinned_admin_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'adv', 'client', ['pinned_admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'adv', type_='foreignkey')
    op.drop_column('adv', 'pinned_admin_id')
    op.drop_column('adv', 'status')
    advertisementstateenum = postgresql.ENUM(AdvertisementStateEnum, name='advertisementstateenum')
    advertisementstateenum.drop(op.get_bind())
    op.drop_table('image')
    # ### end Alembic commands ###
