"""init

Revision ID: 37ec96fe4f75
Revises: 
Create Date: 2022-11-12 14:11:30.009947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ec96fe4f75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('is_vip', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gearbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('engine_type_id', sa.Integer(), nullable=True),
    sa.Column('gearbox_type_id', sa.Integer(), nullable=True),
    sa.Column('based_country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['based_country_id'], ['country.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engine_type_id'], ['engine.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gearbox_type_id'], ['gearbox.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adv')
    op.drop_table('model')
    op.drop_table('producer')
    op.drop_table('gearbox')
    op.drop_table('engine')
    op.drop_table('country')
    op.drop_table('client')
    # ### end Alembic commands ###
