"""sold car

Revision ID: 756bc5a0cbf3
Revises: 03be2435cd77
Create Date: 2022-12-13 13:55:59.596419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import enum

class AdvertisementStateEnum(enum.Enum):
    approved = "approved"
    rejected = "rejected"
    draft = "draft"
    sold = "sold"

# revision identifiers, used by Alembic.
revision = '756bc5a0cbf3'
down_revision = '03be2435cd77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    advertisementstateenum = postgresql.ENUM(AdvertisementStateEnum, name='advertisementstateenum')
    advertisementstateenum.create(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    advertisementstateenum = postgresql.ENUM(AdvertisementStateEnum, name='advertisementstateenum')
    advertisementstateenum.drop(op.get_bind())
    # ### end Alembic commands ###
