"""defaults

Revision ID: 9ec7965056ae
Revises: 660c4b13cbc1
Create Date: 2022-11-30 10:29:34.641272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec7965056ae'
down_revision = '660c4b13cbc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
