"""Update car info

Revision ID: aadb91e45087
Revises: 37ec96fe4f75
Create Date: 2022-11-14 07:29:19.265523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadb91e45087'
down_revision = '37ec96fe4f75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adv', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('adv', sa.Column('engine_volume', sa.Float(), nullable=False))
    op.add_column('adv', sa.Column('range', sa.Integer(), nullable=False))
    op.add_column('adv', sa.Column('description', sa.Text(), nullable=False))
    op.alter_column('adv', 'gearbox_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('adv', 'based_country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client', 'is_vip',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('client', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('client', 'is_vip',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('adv', 'based_country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('adv', 'gearbox_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('adv', 'description')
    op.drop_column('adv', 'range')
    op.drop_column('adv', 'engine_volume')
    op.drop_column('adv', 'price')
    # ### end Alembic commands ###
