"""pinned_admin_id nullable=True

Revision ID: e73370c3ed36
Revises: 765f9ae4801e
Create Date: 2022-11-15 13:58:43.855621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73370c3ed36'
down_revision = '765f9ae4801e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adv', 'pinned_admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adv', 'pinned_admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
