"""big_integer

Revision ID: 03be2435cd77
Revises: 9ec7965056ae
Create Date: 2022-12-03 17:29:59.511415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03be2435cd77'
down_revision = '9ec7965056ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
