"""add drive unit

Revision ID: 099e70e7f6cf
Revises: 4dfb312e6d73
Create Date: 2024-07-03 19:25:47.183430

"""
import json

import requests
from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = '099e70e7f6cf'
down_revision = '4dfb312e6d73'
branch_labels = None
depends_on = None

drives_url = "https://auto.ria.com/api/categories/1/driverTypes?langId=4"
Base = declarative_base()


class DriveUnit(Base):
    __tablename__ = 'drive_unit'
    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.String, nullable=False)



def upgrade() -> None:
    bind = op.get_bind()
    session = Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_unit_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=True),
    sa.Column('drive_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drive_unit_id'], ['drive_unit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filter_id'], ['filter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('adv', sa.Column('drive_unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'adv', 'drive_unit', ['drive_unit_id'], ['id'], ondelete='SET NULL')

    drives_raw = requests.get(drives_url)
    drives = [DriveUnit(name=drive["name"]) for drive in json.loads(drives_raw.text.encode())]
    session.add_all(drives)
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'adv', type_='foreignkey')
    op.drop_column('adv', 'drive_unit_id')
    op.drop_table('drive_unit_filter')
    op.drop_table('drive_unit')
    # ### end Alembic commands ###
