"""add filter drive_unit

Revision ID: 2bcd646b54f2
Revises: 099e70e7f6cf
Create Date: 2024-07-05 17:10:22.101579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bcd646b54f2'
down_revision = '099e70e7f6cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filter', sa.Column('all_drive_units', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filter', 'all_drive_units')
    # ### end Alembic commands ###
