"""add_cloudinary_source_to_image

Revision ID: acf50b6fde26
Revises: a59abbe2d92c
Create Date: 2023-11-03 15:11:16.263863

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.orm import Session

from flask import g

import cloudinary
import requests
import json

from models.image import Image

from app.config import config, init_config

# revision identifiers, used by Alembic.
revision = 'acf50b6fde26'
down_revision = 'a59abbe2d92c'
branch_labels = None
depends_on = None


init_config("/website/settings.ini")

cloudinary.config(
    cloud_name=config["CLOUDINARY"]["CLOUDINARY_CLOUD_NAME"],
    api_key=config["CLOUDINARY"]["CLOUDINARY_API_KEY"],
    api_secret=config["CLOUDINARY"]["CLOUDINARY_API_SECRET"]
)

get_file_url = "https://api.telegram.org/bot{token}/getFile?file_id={file_id}"
file_by_path_url = "https://api.telegram.org/file/bot{token}/{file_path}"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('image', sa.Column(
        'cloudinary_source', sa.String(), nullable=True))

    session = Session(bind=op.get_bind())

    images = session.query(Image).all()

    for image in images[::-1]:
        response = requests.get(get_file_url.format(
            token=config["BOT"]["BOT_TOKEN"], file_id=image.source))
        image_path = response.json()["result"]["file_path"]
        upload_response = cloudinary.uploader.upload(file_by_path_url.format(
            token=config["BOT"]["BOT_TOKEN"], file_path=image_path), folder="autoyarmarok")

        cloudinary_source = upload_response["url"]
        image.cloudinary_source = cloudinary_source
        session.add(image)
    session.commit()

    op.alter_column('image', 'cloudinary_source', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'cloudinary_source')
    # ### end Alembic commands ###
