"""add vin to filter

Revision ID: d53dba9de670
Revises: 62a34f848892
Create Date: 2024-07-09 14:13:21.339716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53dba9de670'
down_revision = '62a34f848892'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filter', sa.Column('vin', sa.Boolean(), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filter', 'vin')
    # ### end Alembic commands ###
