import os

DATABASE_URI = os.environ.get("DATABASE_URI")
BASE_API_URL = os.environ.get("BASE_API_URL")

CLOUDINARY_CLOUD_NAME = os.environ.get("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = os.environ.get("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = os.environ.get("CLOUDINARY_API_SECRET")

API_TOKEN = os.environ.get("API_TOKEN")

CHANNEL_NAME = os.environ.get("CHANNEL_NAME")

MAX_IMAGES = os.environ.get("MAX_IMAGES")

VIP_ADVERTISEMENTS = os.environ.get("VIP_ADVERTISEMENTS")

PAYMENTS_TOKEN = os.environ.get("PAYMENTS_TOKEN")

REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD")
REDIS_USER = os.environ.get("REDIS_USER")
REDIS_USER_PASSWORD = os.environ.get("REDIS_USER_PASSWORD")
